server:
  port: 8002

spring:
  application:
    name: consumer-order-ribbon

eureka:
  instance:
    prefer-ip-address: true
    instance-id: consumer-order-ribbon
  client:
    register-with-eureka: false
client:
  service-url:
    defaultZone: http://eureka8762.com:8762/eureka/,http://eureka8761.com:8761/eureka/,http://eureka8763.com:8763/eureka/


#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /api/doc